changelog:
  exclude:
    labels:
      - documentation
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bugfix 🐛
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
