name: ci

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      run: |
        curl -fL https://github.com/bitrise-io/bitrise/releases/latest/download/bitrise-$(uname -s)-$(uname -m) > /usr/local/bin/bitrise
        chmod +x /usr/local/bin/bitrise

    - name: Test
      run: |
        bitrise run test
      env:
        GITHUB_APP_KEY: ${{ secrets.APP_KEY }}
        GITHUB_APP_ID: ${{ vars.APP_ID }}
